bibliography: bibliography.bib

project:
  type: website
  output-dir: _site

revealjs: 
  slide-number: true
  chalkboard: 
    buttons: false
  preview-links: auto
  theme: dark

execute:
  cache: true
  warning: false

csl: bibstyle.csl

author: Jacopo Tissino
date: 2026-04-24
